#pragma once

enum ImageType
{
	IMAGE_TYPE_UNKNOWN = 0,
	IMAGE_TYPE_PPM_P3,
	IMAGE_TYPE_PPM_P6,
	IMAGE_TYPE_PGM_P5,
	IMAGE_TYPE_PBM_P4,
	IMAGE_TYPE_BMP_24,
	IMAGE_TYPE_BMP_32,
	IMAGE_TYPE_TGA_24,
	IMAGE_TYPE_TGA_32,
	IMAGE_TYPE_TGA_RLE,
	IMAGE_TYPE_PNG_8BIT,
	IMAGE_TYPE_PNG_TRNS,
	IMAGE_TYPE_PNG_PLTE,
	IMAGE_TYPE_PNG_GRAYSCALE,
	IMAGE_TYPE_PNG_16BIT,
	IMAGE_TYPE_PNG_ADAM7,
	IMAGE_TYPE_TIFF_BASELINE,
	IMAGE_TYPE_EXIF_PROPERTIES,
	IMAGE_TYPE_JPEG_BASELINE
};
